---
env:
  PANTS_CONFIG_FILES: "['pants.toml', 'pants.ci.toml']"
  BUILDKITE_PLUGIN_VAULT_ENV_SECRET_PREFIX: "secret/data/buildkite/env"

steps:
  - label: ":lint-roller::bash: Lint Shell"
    command:
      - make lint-shell
    plugins:
      - grapl-security/vault-login#v0.1.2
      - grapl-security/vault-env#v0.1.0:
          secrets:
            - pulumi-buildkite-plugin/TOOLCHAIN_AUTH_TOKEN

  - label: ":lint-roller::buildkite: Lint Plugin"
    command:
      - make lint-plugin

  - label: ":bash: Unit Tests"
    command:
      - make test-shell
    plugins:
      - grapl-security/vault-login#v0.1.2
      - grapl-security/vault-env#v0.1.0:
          secrets:
            - pulumi-buildkite-plugin/TOOLCHAIN_AUTH_TOKEN

  - label: ":buildkite: Plugin Tests"
    command:
      - make test-plugin

  - wait

  - label: ":buildkite::pulumi: Run Plugin - Preview"
    plugins:
      - grapl-security/vault-login#v0.1.2
      - grapl-security/vault-env#v0.1.0:
          secrets:
            - PULUMI_ACCESS_TOKEN
      - "grapl-security/pulumi#${BUILDKITE_COMMIT}":
          command: preview
          project_dir: pulumi/pulumi_buildkite_plugin_test
          stack: grapl/testing
    agents:
      queue: "pulumi-staging"
  
  - wait

  - label: ":buildkite::pulumi: Run Plugin - Preview - with no refresh"
    plugins:
      - grapl-security/vault-login#v0.1.2
      - grapl-security/vault-env#v0.1.0:
          secrets:
            - PULUMI_ACCESS_TOKEN
      - "grapl-security/pulumi#${BUILDKITE_COMMIT}":
          command: preview
          project_dir: pulumi/pulumi_buildkite_plugin_test
          stack: grapl/testing
          refresh: false
    agents:
      queue: "pulumi-staging"

  - wait

  - label: ":buildkite::pulumi: Run Plugin - Update"
    plugins:
      - grapl-security/vault-login#v0.1.2
      - grapl-security/vault-env#v0.1.0:
          secrets:
            - PULUMI_ACCESS_TOKEN
      - "grapl-security/pulumi#${BUILDKITE_COMMIT}":
          command: update
          project_dir: pulumi/pulumi_buildkite_plugin_test
          stack: grapl/testing
    agents:
      queue: "pulumi-staging"
